[options]
addons_path = /mnt/addons,/mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
admin_passwd = $pbkdf2-sha512$600000$qTXmvNcaY4wxhnBurdX63w$AYKvk5hvZiqHK3nTlCUBSwC32y2kz6bnIhEMLJtwVyo1C2xk2XEVGtlHc7WPu.cTf598.zDbGy50rT/EfIUBFA

